title: My Shark Tank Sales Pitch
author: Baegilpong
email: pnguyen003@citymail.cuny.edu
description: > # this means to ignore newlines until "baseurl:"
  This is an assignment for the CS Summer Internship Prep Class
  All things on here are not legitimate and are only there for
  comedic and testing purposes, unless someone is willing  to fund.
theme: minima
# social links
twitter_username: None # DO NOT include the @ character, or else the build will fail!
github_username:  Baegilpong # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
